# Generated by Django 5.1 on 2024-11-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_grammarrule_script_audience_level_examplesentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('vocabulary', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=10)),
                ('explanation', models.TextField()),
            ],
        ),
    ]
