# Generated by Django 5.1 on 2024-11-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_questionmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmeta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
